# brew bundle --global
cask_args appdir: "~/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "cmake"
brew "readline"
brew "docutils"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "graphviz"
brew "gpg"
brew "gnupg"
brew "imagemagick"
brew "java"
brew "libjpeg"
brew "librsvg"
brew "libtiff"
brew "libxmlsec1"
brew "libxslt"
brew "little-cms2"
brew "nodenv"
brew "openconnect"
brew "openssl"
brew "pipenv"
brew "postgresql"
brew "pyenv"
brew "rbenv"
brew "redis"
brew "sqlite"
brew "webp"
brew "xz"
brew "yarn"
brew "zlib"
brew "zsh"
brew "fasd"
brew "docker-compose"
brew "markdown"
# https://stackoverflow.com/a/40066889
brew "pinentry-mac"

cask "docker"
cask "slack"
cask "1password"
cask "google-chrome"
cask "emacs"
cask "alfred"
cask "spectacle"
cask "whatsapp"
cask "spotify"

