name: Build and Push Docker Image

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  push:
    # Trigger the workflow when changes occur in the bootc/ directory
    paths:
      - 'bootc/**'
  workflow_dispatch: # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image from the Containerfile
      - name: Build Docker image
        run: |
          docker build -f bootc/Containerfile -t docker.io/siegy22/fedora-bootc:latest bootc/

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push docker.io/siegy22/fedora-bootc:latest

